### ISSUE TITLE
Hardware reference and sample code

### ISSUE THREAD

**Issue by hilsonp** [Wiz-IO/wizio-cc#2]
Hi Georgi,

Nice work ! I mean : awesome work.
I read all threads on TI, looked at your videos and everything I could find you published.

I would like to create a module that:
- can blink a led => digitalWrite()
- can control a stepper motor => digitalWrite()
- can read contact state => digitalRead()
- is battery powered => zigbee
- can report securely the state of the contact and motor => zigbee
- can receive securely orders (to move motor) => zigbee

From what I see in this video, this seems possible: https://www.youtube.com/watch?v=_QHe3rqxSYc
Would you mind sharing the hardware and the code you used for this video.
I checked https://github.com/Wiz-IO/examples-wizio-cc but could not find it.

Is that this hardware:
https://www.aliexpress.com/item/1005004443820263.html

Thank you VERY MUCH in advance,

Pierre
Note: I'm a bit surprized by the lack of interest in your videos/posts/github repos because, as far as I could see, this is the best resource I found for an hobbyist to create a zigbee module.

**Comment by Wiz-IO** [comment]
Hi
Thanks

you can use any CC2652 boards from AliExpress, aBay....
I have this boards
https://www.ebay.com/itm/255121247590
https://www.tindie.com/products/electrolama/zzh-cc2652r-multiprotocol-rf-stick/

**Comment by hilsonp** [comment]
Great. Thank you. 

Can you tell me where I can find the code used in this video?
This will be a good basis for me. 

Second question: The goal is to run on batteries. Will I be able to deep sleep and wake on  interrupts ?

Thank you.

**Comment by Wiz-IO** [comment]
example from video use hacked ZBOSS library
TI not support ZBOSS ( is a paid library )

**Comment by hilsonp** [comment]
Thank you for your quick replies.
